// Auto-generated by boneyard-js CLI.
// Run: npx boneyard-js build http://localhost:5173
// This file is overwritten on every build — do not edit manually.
// It is committed as a placeholder so the import in main.jsx doesn't crash
// before the CLI has been run for the first time.
