import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import ErrorBoundary from './components/ErrorBoundary';

// boneyard-js: auto-resolves skeleton bones by name for all <Skeleton> components.
// Generated by: npx boneyard-js build http://localhost:5173
// Re-run after UI changes to keep skeletons in sync.
import './bones/registry'

ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
        <ErrorBoundary>
            <App />
        </ErrorBoundary>
    </React.StrictMode>,
)